MVCLearning/Controllers/ViewsDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCLearning.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MVCLearning.Controllers
{
    public class ViewsDemoController : Controller
    {
        private EventsAndMenusContext _context;
        public ViewsDemoController(EventsAndMenusContext context) => _context = context;

        public IActionResult Index() => View();

        public IActionResult PassingData()
        {
            ViewBag.MyData = "Hello from the controller";
            return View();
        }

        private IEnumerable<Menu> GetSampleData() =>
            new List<Menu>
            {
                new Menu
                {
                    Id=1,
                    Text="Schweinsbraten mit Knödel und Sauerkraut",
                    Price=6.9,
                    Category="Main"
                },
                new Menu
                {
                    Id=2,
                    Text="Erdäpfelgulasch mit Tofu und Gebäck",
                    Price=6.9,
                    Category="Vegetarian"
                },
                new Menu
                {
                    Id=3,
                    Text="Tiroler Bauerngröst'l mit Spiegelei und Krautsalat",
                    Price=6.9,
                    Category="Main"
                }
            };

        public IActionResult PassingAModel() => View(GetSampleData());

        public IActionResult LayoutSample => View();

        public IActionResult LayoutUsingSections() => View();

        public IActionResult UseAPartialView1() => View(_context);

        public ActionResult UseAPartialView2() => View();

        public ActionResult ShowEvents()
        {
            ViewBag.EventsTitle = "Live Events";
            return PartialView(_context.Events);
        }

        public IActionResult UseViewComponent1() => View();

        public IActionResult InjectServiceInView() => View();
    }
}

MVCLearning/ViewComponents/EventListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCLearning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCLearning.ViewComponents
{
    public class EventListViewComponent : ViewComponent
    {
        private readonly EventsAndMenusContext _context;
        public EventListViewComponent(EventsAndMenusContext context) => _context = context;

        public Task<IViewComponentResult> InvokeAsync(DateTime from, DateTime to) =>
            Task.FromResult<IViewComponentResult>(View(EventsByDateRange(from, to)));

        private IEnumerable<Event> EventsByDateRange(DateTime from, DateTime to)
        {
            return _context.Events.Where(e => e.Day >= from && e.Day <= to);
        }
    }
}

MVCLearning/Views/ViewsDemo/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Index</title>
</head>
<body>

</body>
</html>

MVCLearning/Views/ViewsDemo/InjectServiceInView.cshtml
@inject ISampleService sampleService
<p>
    @string.Join(" * ", sampleService.GetSampleStrings())
</p>

MVCLearning/Views/ViewsDemo/LayoutSample.cshtml
@{
    ViewData["Title"] = "Layout Sample";
}
<h2>Layout Sample</h2>
<p>
    This content is merged with the layout page
</p>

MVCLearning/Views/ViewsDemo/LayoutUsingSections.cshtml
@{
    ViewBag.Title = "Layout Using Sections";
}
<h2>Layout Using Sections</h2>
<div>Main content here</div>
@section PageNavigation
    {
    <div>Navigation defined from the view</div>
    <ul>
        <li>Nav1</li>
        <li>Nav2</li>
    </ul>
}

MVCLearning/Views/ViewsDemo/PassingAModel.cshtml
@model IEnumerable<Menu>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Passing A Model</title>
</head>
<body>
    <div>
        <ul>
            @foreach (var item in Model)
            {
                <li>@item.Text</li>
            }
        </ul>
    </div>
</body>
</html>

MVCLearning/Views/ViewsDemo/PassingData.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Passing Data</title>
</head>
<body>
    <div>
        <div>@ViewBag.MyData</div>
    </div>
</body>
</html>

MVCLearning/Views/ViewsDemo/ShowEvents.cshtml
@model IEnumerable<Event>
<h2>
    @ViewBag.EventsTitle
</h2>
<table>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Day.ToShortDateString()</td>
            <td>@item.Text</td>
        </tr>
    }
</table>

MVCLearning/Views/ViewsDemo/UseAPartialView1.cshtml
@model EventsAndMenusContext
@{ 
    ViewBag.Title = "Use a Partial View";
    ViewBag.EventsTitle = "Live Events";
}
<h2>Use a Partial View</h2>
<div>This is the main view</div>
<div>
    @await  Html.PartialAsync("ShowEvents", Model.Events)
</div>

MVCLearning/Views/ViewsDemo/UseAPartialView2.cshtml
@model EventsAndMenusContext
@{
    ViewBag.Title = "Use a Partial View";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    (function () {
        window.onload = function () {
            var buttonEvents = document.getElementById("getEvents");
            buttonEvents.onclick = function () {
                if (window.fetch == null) {
                    output.innerHTML = "<div>window.fetch not supported. Use another browser</div>";
                    return;
                }
                var result = fetch("/ViewsDemo/ShowEvents");
                result.then(function (response) {
                    return response.text();
                }).then(function (text) {
                    var output = document.getElementById("output");
                    output.innerHTML = text;
                });
            };
        };
    })();
</script>
<h2>Use a Partial View</h2>
<div>this is the main view</div>
<button id="getEvents">Get Events</button>
<div id="output">
</div>

MVCLearning/Views/ViewsDemo/UseViewComponent1.cshtml
@{ 
    ViewBag.Title = "View Components Sample";
}
<h2>@ViewBag.Title</h2>
<p>
    @await  Component.InvokeAsync("EventList", new Dictionary<string, object>()
    {
        ["from"] = new DateTime(1999, 10, 8),
        ["to"] = DateTime.Now
    })
</p>